version: '3.8'

services:
  postgres:
    image: postgres
    container_name: seller-db-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: database-seller
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - seller-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  seller-network:
    driver: bridge
