spring:
  application:
    name: ppm-delivery-seller-api-service

  datasource:
    url: jdbc:postgresql://localhost:5432/database-seller
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver



