spring:
  application:
    name: ppm-delivery-seller-api-service

  datasource:
    url: jdbc:postgresql://localhost:5432/database-seller
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  seller:
    supportedCountries:
       - BR
       - AR
       - CO
       - MX
       - PY
       - US

